[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
startCommand = "sh -c 'npm run db:migrate && node dist/main.js'"
healthcheckPath = "/api"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10